### ISSUE TITLE
run line

### ISSUE THREAD

**Issue by vnijs** [skranz/shinyAce2#1]
@skranz Thanks for the extensions you wrote for shinyAce! The hotkeys function is great. I have been using it to knit rmarkdown files and run R-code inside a shinyapp (https://github.com/vnijs/radiant).

Would it be possible to select the current line automatically and then move the cursor down one line? Like in Rstudio basically. I looked at your `examples/acetest.r` but there the selection would be based on the position of the cursor.

**Comment by skranz** [comment]
Dear Vincent,

thanks for your email. I don't know whether it is possible to select the 
line and then move the cursor, but I guess the functionality is in the 
ace editor:

https://groups.google.com/forum/#!topic/ace-discuss/GyMgLAj5de4

So I guess this could also be implemented in shinyAce. But I am also not 
really an expert on shiny bindings with javascript (including the 
hotkeys was mostly try-and-error adaption of the existing shinyAce 
code). So maybe just fork shinyAce and try out a bit, how you can call 
the corresponding javascript methods of the ace editor from R with shiny.

BTW: radiant looks really nice useful!

Best wishes,
Sebastian

Am 20.05.2015 um 21:08 schrieb Vincent Nijs:

> @skranz https://github.com/skranz Thanks for the extensions you 
> wrote for shinyAce! The hotkeys function is great. I have been using 
> it to knit rmarkdown files and run R-code inside a shinyapp 
> (https://github.com/vnijs/radiant).
> 
> Would it be possible to select the current line automatically and then 
> move the cursor down one line? Like in Rstudio basically. I looked at 
> your |examples/acetest.r| but there the selection would be based on 
> the position of the cursor.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/skranz/shinyAce2/issues/1.

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by vnijs** [comment]
Thanks for the reply @skranz. I'll see what I can do but it will, at best, be trial-and-error as well.
